### ISSUE TITLE
Documentation: add debugging configuration steps (specifically VS code)

### ISSUE THREAD

**Issue by cmeyertons** [vuestorefront/vue-storefront#1810]
## What is the motivation for adding / enhancing this feature?
The application architecture is very good, but also very advanced.  Someone new to the project may not easily be able to set up debugging a Node.js process inside a docker container trivially.  Plus every new person coming in has to do this probably at some point, so why re-invent the wheel?

Since VS code is already the recommended IDE, a possibility is to commit a dev's `.vscode` folder.  If committed as is, it would change someone's tailored setup (not good!).  So instead, we could commit either as `.vscode-default` folder or rename each file w/ a .default suffix (launch.default.json) -- which is inline w/ the config folder setup process.

# Can you complete this feature request by yourself?
NO (I'm one on the new devs struggling w/ this!)

**Comment by pkarw** [comment]
@NataliaTepluhina could You please take care of this one?

**Comment by NataliaTepluhina** [comment]
@pkarw will look into it

**Comment by cmeyertons** [comment]
hello, I ended up getting this set up using the [vs code docs](https://github.com/Microsoft/vscode-recipes/tree/master/Docker-TypeScript) for the API project.

I'm going to create a PR against the api project and will reference this issue

**Comment by liborpansky** [comment]
Have you created the PR? I was struggling with Vue Storefront API debug today (it should be probably part of [Vue Storefront API repository](https://github.com/DivanteLtd/vue-storefront-api), but there's already closed issue [no. 117](https://github.com/DivanteLtd/vue-storefront-api/issues/117)), finally I got it working. I'm not sure how you debug API with current settings, but according to [Nodemon debug tutorial](https://github.com/Microsoft/vscode-recipes/tree/master/nodemon) I had to add a new script in package.json with following configuration: (change `-w` parameter to `--inspect`)
```
"debug": "nodemon --inspect src --exec \"babel-node src --presets env,stage-0\"",
```
Then I created a new VS Code launch configuration to attach to a node process:
```
{
  "type": "node",
  "request": "attach",
  "name": "Attach to Nodemon process",
  "processId": "${command:PickProcess}",
  "restart": true,
  "protocol": "inspector",
}
```
After launching a `yarn debug` command I start debugging in VS Code selecting nodemon node process:
![image](https://user-images.githubusercontent.com/9642342/50596743-88431080-0ea5-11e9-8428-82cf1c9ac12e.png)

Is there a better way how to debug Storefront API? I suppose you debug in a different way, otherwise debug script would be already present in package.json...

**Comment by mojo2012** [comment]
But this is only for the frontend part right? But what about debugging the core?

**Comment by jahvi** [comment]
Can confirm @ananth-iyer code works, not sure how it does without `--inspect` though.

@mojo2012 This should work everywhere in VS, or did you mean vue-storefront-api?

**Comment by ananth-iyer** [comment]
@mojo2012 It works on typescript, vuejs on `vue-store-front-api`
@jahvi I will post an video on Monday with full detail
