### ISSUE TITLE
Filters and attributes on Category page should be loaded dynamically

### ISSUE THREAD

**Issue by pkarw** [vuestorefront/vue-storefront#2179]
## What is the motivation for adding / enhancing this feature?

Currently, You must set all available filters in the `config.products.defaultFilters`. It would be much better to load the list of the filterable attributes based on the search results (attributes of the products returned)

Related to #1975 

As this change may affect the performance (much more attributes to be loaded) - we probably need to add a config option for enabling/disabling this feature

## What are the acceptance criteria 

* The filter list is generated automatically and all possible attributes used in filters are dynamically loaded without the need to modify the config

**Comment by lukeromanowicz** [comment]
@pkarw 
some backends like Magento allow to define which attributes might be searchable and how to handle every one of them. Do we take it into account while developing this feature?

**Comment by pkarw** [comment]
We should. We do have this info in the attribute entities so we should get the attribute codes from products results and then load these attributes (attribute/list) and check which ones are used for filters

**Comment by pkarw** [comment]
I belive that the simplest way to solve this issue is to modify the core to dynamically load the attributes to aggregate on based on the search result or just by the config (but not by config.products.defaultFIlters but rather by new settiings setb y category - like: config.products.defaultFiltersFor { 542: { filters for categorty 542 and subcategories }}

**Comment by pkarw** [comment]
@patzick one of our best clients has a problem with the performance just by this issue (ask @lukeromanowicz for details); it would be great to handle it with the category refactor for 1.11

**Comment by pkarw** [comment]
@patzick is this one still a case?

**Comment by patzick** [comment]
Current state: indexer should be upgraded to add available filters for every category. Filters should be fetched from Magento. After that frontend app can be changed to use this config from the category object.

**Comment by pkarw** [comment]
@gibkigonzo what do you think about it? I mean after https://github.com/DivanteLtd/vue-storefront/pull/3988 merged in - maybe we could somehow construct the filters based on what comes in with `attributes_metadata`?

The other option is as @patzick suggested modify the indexers to add the filers per category (`filters_metadata`) per categories; Wdyt?

**Comment by gibkigonzo** [comment]
@pkarw all available filters for specific category page are in `attributes_metadata`. We just need to add flag to attribute like `is_filter` and then just map it on frontend. Can we get that flag for attribute from magento?

**Comment by dkarlovi** [comment]
@pkarw the common approach I've seen used (and used myself when implementing this) is to store attributes in an array (suggested just now in #4812), create an aggregate on that and then use the aggregates to build the filters, it means whatever ends up in the array can become a filter right away.

**Comment by dkarlovi** [comment]
One thing I've noticed, please correct me if I'm wrong:
![Women-Vue-Storefront](https://user-images.githubusercontent.com/209225/92470900-6439e580-f1d7-11ea-99ad-45f39d65e444.png)

- I'm able to specify the desired labels for **filters' values** via `attributes.<attribute>.options[].label`
- I'm not able to specify the desired labels for the *filter* itself, except via translations committed directly into VSF source

If so, this is definitely an issue to be solved together here since that data is obviously also to be loaded dynamically if this issue is to be solved. It seems the proper place would be `attributes.<attribute>.label`, no?

TBH the current situation with attributes, their loading and metadata in general could use some redesign and/or more documentation, currently I'm piecing this info together from several places, not really efficiently.
