### ISSUE TITLE
Doc of production setup docker/kubernetes unclear/missing

### ISSUE THREAD

**Issue by danielvanmil** [vuestorefront/vue-storefront#2365]
## What is the motivation for adding / enhancing this feature?
The documentation at : https://docs.vuestorefront.io/guide/installation/production-setup.html#production-setup-using-docker-kubernetes is in status 'To be prepared.', but it is unclear what the status of this topic is.

## What are the acceptance criteria 

* ...
* ...

# Can you complete this feature request by yourself?

**Comment by pkarw** [comment]
This is feature request - it has not yet been described :)

**Comment by simonmaass** [comment]
would love this addition!

**Comment by waynetheisinger** [comment]
On my project I will be setting up in docker/kubernetes - I don't mind taking on documenting this as part of the project... If anyone has done a build like this feel free to give pointers or gotcha's

**Comment by simonmaass** [comment]
@waynetheisinger thank you!

**Comment by waynetheisinger** [comment]
Hi @pkarw - as I said above I'm taking on this task, feel free to assign it to me to stop someone else also working on it. 

The `/kubernetes/*.yaml` files as they exist at the moment are only useful for local development and can't be used as templates for production because they assume that most of the folders exist on the host, which obviously they won't in production. I can document how they can be translated to production templates or we can provide another directory with /kubernetes-production-templates, what would your preference be?

Secondly from my first examination I am beginning to think that nothing needs to be persisted beyond the lifetime of the pod and therefore if `dist` and `var` are `emptyDir` volumes we don't actually need any extra persistence volumes. Do you agree?

Finally in horizontal scaling if when running `yarn migrate` and `yarn dump` you have kubectl in to one pod container - it is irrelevant that other pods exist because Elasticstore is the persistence and the jason files in `var` are just ephemeral therefore other pods & containers don't need to know about them... again do you agree?

**Comment by pkarw** [comment]
hi @waynetheisinger thanks for taking this task; I'm not a devops expert neither kubernetes hard user so it's very hard for me to answer - maybe some other folks will have anything to add? it soundds reasonable what you wrote :)

**Comment by kkdg** [comment]
@waynetheisinger I am feeling free to stop working on this, although it has been stacked to the queue and didn't get the much attention to get going :) thanks (well, however, I won't stop it forever since we have our own format to wrap up the topic. I will also be working on it when my queues become relaxed, in that time  your part will be a great help to that format too. Thanks!)

**Comment by waynetheisinger** [comment]
No problem - I had to move to another project this week but I'm back on this next week... I'll comment here to let you know when I make pushes to my fork so that you can keep an eye on things before I do a formal Pull Request back to the main project...

**Comment by themreza** [comment]
Any updates on this?

**Comment by dhouhamaa** [comment]
Is there any update ? am currently trying to run the app o kubernetes without any luck ! It worked with docker and I used the docker images in the kubernetes yaml files but sill no good result .

**Comment by waynetheisinger** [comment]
OK the project that I was working on that dovetailed with this documentation was shelved so I never got going on it. However, another has just started so I'm back on this now.

Sorry for the delay and we should get some traction now.. 😄

**Comment by bloodf** [comment]
This issue has been closed due to inactivity. 

If you want to re-open the issue, please re-create the issue, and post newer information on this problem.
