### ISSUE TITLE
Optimize cart/sync actions

### ISSUE THREAD

**Issue by andrzejewsky** [vuestorefront/vue-storefront#3375]
## What is the motivation for adding / enhancing this feature?
Some cart actions cause sending many API requests to do simple actions eg. adding or removing products to/from the cart. Sometimes user can see some part of the UI that have not refreshed yet even though he has triggered some changes or sometimes it takes really long. Would be nice to sort out with that.

## What are the acceptance criteria 
* [ ] reduced number of api calls

## Can you complete this feature request by yourself?
* [ ] YES
* [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
* [x] This is a normal feature request. This should be available on https://test.storefrontcloud.io and then after tests this can be added to next Vue Storefront version. In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
* [ ] (**Pick this option only if you're sure**) This is an important improvement request for current Release Candidate version on https://next.storefrontcloud.io and should be placed in next RC version. In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
* [ ] (**Pick this option only if you're sure**) This is a critical improvement request for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version. In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

**Comment by pkarw** [comment]
The first thought was to move the whole “cart/sync” plus “cart/merge” to vsapi - and sending out just the json with the current cart and the server cart token and perform the merge server side. It should be optional behavior (to the current one in order to keep the backward compatibility and support some use cases like 1k+ lines orders where sending the whole cart to server just for sync makes a little sense and the current behavior could be more optimal). It should be selected (the server or client sync) by the config: config.cart.serverSideSync (default false)
