### ISSUE TITLE
Massive delay in serving cached content

### ISSUE THREAD

**Issue by lukeromanowicz** [vuestorefront/vue-storefront#4125]
## Current behavior
There is a 90-150ms delay between connection and serving cache from content present on stock vue storefront. Express is capable of responding with less than 1ms TTFB so it looks like some issue with VSF codebase. 

![image](https://user-images.githubusercontent.com/46789227/75364993-d93d7180-58bc-11ea-857e-e63606fb1a3e.png)

## Expected behavior
serving cached content in 20-50ms, not 200ms+

## Steps to reproduce the issue
1. enable redis cache in frontend
1. test ttfb on a cached page

## Can you handle fixing this bug by yourself?
* [x] YES
* [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

* [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
* [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
* [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

**Comment by pkarw** [comment]
Good point. Is this result from your local instance/storefrontcloud/other?

One of the solutions is this: https://github.com/ClickAndMortar/docker/tree/master/vue-storefront/proxy/lua (it will be automatically deployed to all SC instances soon, currently tested in Zadig&Voltaire - developed by these folks).

There could be many reasons for this delay; if it’s
On the cloud we already have some findings with @mkoszut so we can share - usually it’s related to the pm2 process saturation / event loop caused by the other requests (eg. image resize)

**Comment by pkarw** [comment]
Somehow related: #4089 
Related to: #4096, #4094

**Comment by lukeromanowicz** [comment]
It's partially dependent on NodeJS version. Using Node 13 instead of Node 10 made about 30% improvement. That being said it's still a case both on demo cloud and my local environment. I know for a fact though that @ResuBaka is not experiencing this issue on his Arch-based setup.

**Comment by ResuBaka** [comment]
I can give here some info from my debugging. 

Nodejs 10
Google Cloud NB2 n2d-standard-2
Ubunut 18LTS 
Kernel 5.0: Has the problem
Kernel 5.5: Has the problem
Centos8: Has the problem

> All had nearly the same times +/-5ms, but over all +100ms from when the cache function sends the request and the TTFB happens. 

The problem looks like a delay when nodejs sends the request to the operation system and the response of it. 

As the cache time and the reg.on('finish') call take the same time ~44ms and after that the ttfb is ~120ms. 

That sad locally on my Manjaro setup I don't have that problem and on the System of one of my Coworkers (Ubuntu 18LTS) the problem is not there same behavior as for me.

My timings locally with node 10 or  node 13 are cache time 13ms und reg.on('finish') 13ms and a ttfb of 25ms. 

On all the systems the redis was on the local system and the curl command was `curl -D - --output /dev/null  -H 'Cache-Control: no-cache' -s -w "Connect: %{time_connect} TTFB: %{time_starttransfer} Total time: %{time_total} \n" http://localhost:3000`.

For me it looks like some config settings of the Linux Setup, but there I have not looked into it if there are some network stack setup that may could cause this issue.

I hope these info helps when some body else is looking into this issue.

**Comment by cewald** [comment]
I noticed that it makes a huge different if I send a **server-side** request, using HTTP1 or HTTP2. Especially in the `vue-storefront`. This might be a bit off-topic and maybe not directly connected to the problem above – but as I tried to trace down where this latency came from, I saw that all common request libs like `axios`, `node-fetch` or `node-request` do not support HTTP2 – so I tried it by implementing it using the nodejs' native HttpRequest class, and it was noticeable faster, especially for large responses. So – it could bring an improvement of TTFB when a request is made on the server-side during the request.

**Comment by pkarw** [comment]
That's interesting observation @cewald any ideas how to fix it?

**Comment by cewald** [comment]
@pkarw In our case I refactored the connector for our CMS inside the API that makes HTTP requests to external services (Storyblok CMS) using the `http2-client` node library. It's not as convenient as `node-request` or `axios` but you're able to use the benefits of HTTP2.

**Comment by pkarw** [comment]
@lukeromanowicz @cewald guys maybe we should create a set of tasks based on this one? I mean it's kind of epic. There is no single solution as it depends on multiple factors relative to the prod. env mostly

wdyt?
