### ISSUE TITLE
Dynamically injected component don't contain i18n

### ISSUE THREAD

**Issue by bottle93** [vuestorefront/vue-storefront#4206]
## Current behavior

Mounting components out of template tree results in internationalization (i18n) and probably other global mixins not working.

`// Dynamically inject a component into the order review section (optional)
          const Component = Vue.extend(InfoComponent)
          const componentInstance = (new Component())
          componentInstance.$mount('#checkout-order-review-additional')`

## Can you handle fixing this bug by yourself?
* [ ] YES
* [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

* [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
* [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
* [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

* Browser: 
* OS: 
* Node: 
* Code Version:

**Comment by pkarw** [comment]
Please provide us with an information about the VSF version you're encountering this issue with. I guess you shouldn't instantiate the `Component` class itself because it won't have any mixins attached and it's probably not an issue but standard Vue behavior. @filrak @andrzejewsky correct me if I'm wrong?

**Comment by bottle93** [comment]
VSF version 1.11.2

It's taken from https://github.com/DivanteLtd/vue-storefront/blob/master/src/modules/payment-cash-on-delivery/index.ts#L52

i18n, store, and other global mixins are not working in the InfoComponent, as you've noticed. What is the correct way to handle it? Why this component is not rendered as a part of the template?

**Comment by gibkigonzo** [comment]
### Why this component is not rendered as a part of the template?
That because each payment method can have different component inside module directory. So we want to inject this instead of hardcoding in component.

### What is the correct way to handle it?
I think this can be done in better way, but I'm sure it will make breaking change.
Instead of that https://github.com/DivanteLtd/vue-storefront/blob/master/src/modules/payment-cash-on-delivery/index.ts#L50-L52
we can add global component `Vue.component('checkout-order-review-additional', InfoComponent)`

which can be used here: https://github.com/DivanteLtd/vue-storefront/blob/master/src/themes/default/components/core/blocks/Checkout/OrderReview.vue#L25-L29
```
        <div id="checkout-order-review-additional-container">
          <checkout-order-review-additional v-if="$options.components['checkout-order-review-additional']" />
        </div>
```

and reset here:
https://github.com/DivanteLtd/vue-storefront/blob/master/core/modules/checkout/components/Payment.ts#L243
`delete (Vue as any).options.components['checkout-order-review-additional']`

Current approach will work only if we pass same options to `new Component()` as we pass to app, which will result in creating again whole app (with different scope) just to render one simple component. https://github.com/DivanteLtd/vue-storefront/blob/master/core/app.ts#L80-L85
