### ISSUE TITLE
Switch to `storefront-api`, set the `vue-storefront-api` deprecated

### ISSUE THREAD

**Issue by pkarw** [vuestorefront/vue-storefront#4210]
## What is the motivation for adding / enhancing this feature?

With the 1.13rc1 we should switch from `vue-storefront-api` to `storefront-api`. It's a `vue-storefront-api` refactored and TypeScripted. 100% compliant with VSF

ResuBaka what do you think? Will we be able to release the current `develop` (including packages) till this time? I mean realistically it will be July :)

**Comment by ResuBaka** [comment]
"100% compliant with VSF" I would currently more say 90% to 99%. When it comes to the api extensions, but when it comes to the external api e.g. Products/Category/... these are 100% compliant with the current vue-storefront-api.

For getting the storefront-api to 1.0.0 we should over all just look what still needs to be done so that is in a state where it is in a state where it is fine to release to every body. So is some basic docs, there are all the APIs internally that developers need to extend it to there needs.

**Comment by pkarw** [comment]
We need to update: 
- [ ] `docs` (regarding the installer and all the other sections), 
- [ ] `installer`, 
- [ ] `cli`,
- [ ] put some notes to the `vue-storefront-api` repo
