### ISSUE TITLE
Incorrect Product photo and breadcrumbs for group product.

### ISSUE THREAD

**Issue by alinadivante** [vuestorefront/vue-storefront#4284]
## Current behavior
When switching to group product from the cart, the photo and breadcrumbs are not updated.

![image](https://user-images.githubusercontent.com/36628922/80216947-2b8ddb00-863f-11ea-9e19-034c0486b489.png)

## Expected behavior
The appropriate product photo should be displayed.

## Steps to reproduce the issue
1. Add following group-product https://next.storefrontcloud.io/gear/gear-3/set-of-sprite-yoga-straps-2046.html
1. Add other product, eg https://next.storefrontcloud.io/women/tops-women/tees-women/tees-25/karissa-v-neck-tee-1529.html?childSku=WS10-M-Green
1. Open minicart
1. Press `Sprite Yoga Strap 8 foot` link

## Can you handle fixing this bug by yourself?
* [ ] YES
* [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

* [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
* [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
* [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

* Browser: 
* OS: 
* Node: 
* Code Version:

**Comment by gibkigonzo** [comment]
TODO:
we need to do same approach as for configurable product https://github.com/DivanteLtd/vue-storefront/pull/4426

**Comment by gibkigonzo** [comment]
This problem occurs because when you click on product in cart, it is simple product with visibility === 1. To fix that we need to check if product has parent and visibility === 1 before we enter route. So best place to do that is mappingFallback
Steps:
- check if product has visibility === 1
- check config
- make search for different parent in one query - this can be done in 1.12
- disable adding route mapping for product that has visibility === 1

This can be done in 1.11, but we need to have ability to create one query for parent for different type of product. So this will be fixed in 1.12.
Here is solution for 1.11 of someone needs that https://github.com/DivanteLtd/vue-storefront/compare/hotfix/v1.11.4...gibkigonzo:bugfix/4284?expand=1
