### ISSUE TITLE
Vuepress doesn't support task lists

### ISSUE THREAD

**Issue by lukeromanowicz** [vuestorefront/vue-storefront#4391]
## Current behavior
Tasks list is not supported by vuepress
eg. 

```
- [ ] unchecked
- [x] checked
```

![image](https://user-images.githubusercontent.com/46789227/81805752-b74aa700-951b-11ea-831b-28f8e38b663e.png)

## Expected behavior
![image](https://user-images.githubusercontent.com/46789227/81805799-c9c4e080-951b-11ea-8258-ca3d3513361d.png)

┆Issue is synchronized with this [Jira Story](https://vsf.atlassian.net/browse/NEXT-119) by [Unito](https://www.unito.io/learn-more)

**Comment by Qrzy** [comment]
It's because those checkboxes are specific to GFM (GitHub Flavoured Markdown).
It uses markdown-it to process the `.md` files thus follows mainly [CommonMark spec](http://spec.commonmark.org/).
If there is a plugin for markdown-it to handle those checkboxes, we can add it:
https://vuepress.vuejs.org/guide/markdown.html#advanced-configuration

**Comment by lukeromanowicz** [comment]
@Qrzy that's correct. There is a plugin: https://github.com/revin/markdown-it-task-lists
