### ISSUE TITLE
unexpect behavior in compare list 

### ISSUE THREAD

**Issue by msalah20** [vuestorefront/vue-storefront#4864]
## Current behavior
Some products have 'Activity' paramter displayed in designated line in compare view. It displays properly, if product was added using 'add to compare' button on PDP. However, when the same product is added with button from PLP, this line in compare view will not appear.

For some reason, this parameter dont seem to be transfered, when we add product to compare using buttons from PLP (see scenario 2)

Scenario 1.

Steps to repoduce:

```
On fresh instance (clear cache etc.) go to gear, fitness equipment category.
Add 'Go-Get'r Pushup Grips' to compare from PLP view
Open compare list
Now remove it, and go to the same product detail page
Add product to compare again, this time from PDP.
```

Current behavior:
After step 3, 'Activity' parameter is missing from compare view.
After step 5, 'Activity' is correctly displayed there
![bug](https://user-images.githubusercontent.com/71206268/93115624-665ee100-f6bc-11ea-9cea-18fc17a9f9c1.PNG)

Expected behavior
If parameter is present for a product, it should be visible in compare list. no matter how we add product there.
Scenario 2:

Steps to reproduce:

```
On fresh instance (clear cache etc.) go to gear, fitness equipment category.
Open 'Sprite foam Roller' PDP and add it to compare from there
Open compare window - "activity parameter should be displayd for the product. close compare.
Go back to category view and add 'Go-Get'r Pushup Grips' from PLP view.
Open compare window again
```

Current result:
Foam roller has it's activity correctly displayed. Pushup grips have N/A there - while we know, this product have activity parameter as well
![compare](https://user-images.githubusercontent.com/71206268/93115715-8db5ae00-f6bc-11ea-9782-85115c5dce34.PNG)

 Environment details

* Browser: latest Chrome
* OS: Ubuntu 18.04
*  Node: 10.22.0
* Magneto: 2.4 CE

**Comment by msalah20** [comment]
@pkarw help me ?

**Comment by gibkigonzo** [comment]
@msalah20 Compare list is saved only in LocalStorage. On PDP we have full product data, but on PLP there are only necessary attributes (for example there is no description because we don't display it on PLP). So when you add product from PDP you have full data in LS and when you do same thing from PLP then some attributes may be missing. You can solve this problem by extending `config.entities.productList.includeFields` with needed attributes. Maybe we can add some kind of invalidation for compare list based on config. @Fifciu
