### ISSUE TITLE
Set extractCSS as default setting in nuxt.config.js

### ISSUE THREAD

**Issue by andrzejewsky** [vuestorefront/vue-storefront#4890]
Due to performance reasons and weird css ordering in production mode, would be nice to set `extractCSS` setting for nuxt.js

ref: https://nuxtjs.org/api/configuration-build/#extractcss

**Comment by RWave88** [comment]
@andrzejewsky I would argue that setting `extractCSS` to `true` will actually get you into those ordering issues as described here: https://github.com/nuxt/nuxt.js/issues/4219
although the task is closed - it's still reproducible even on the latest version of Nuxt.
Moreover in most cases extracting CSS into a separate chunk (especially for pages) will give you issues with performance rather than any gains due to the fact that serving one additional request is longer than parsing css from already loaded chunk. It can only be beneficial if you got external css of more than 1mb, but on the other hand if you have to serve so much CSS I would rather ask myself what made me create so much CSS in the project, usually most of it is dead/not used/not needed for a requested page state, so rather than extracting CSS you should reduce it's size
