### ISSUE TITLE
useInventory for core

### ISSUE THREAD

**Issue by filrak** [vuestorefront/vue-storefront#4968]
# useInventory
`useInventory` is a composable thats only responsibility is to check the inventory data about a certain product like stock quantities, delivery time, in-store availability etc.

The task is to:

* implement core factory (incl `customQuery`)
* implement boilerplate mock
* implement CT mock (just copy from BP)
* implement UI for PDP ( https://www.figma.com/file/N0Ct95cSAoODNv7zYS01ng/Storefront-UI-%7C-Design-System?node-id=4472%3A10819 )

## API
```js
const { inventory, search, loading, error } = useInventory()

search({ id })

```

```ts
interface InventorySearchParams {
  id: string | string[]
}
```

**Getters**

```
// all return numbers
getOnStockQty  // total number of items on stock
getReservedQty // number of reserved items
getAvailableQty // number of items available to buy (not reserved)
getExpectedDeliveryTime //  delivery time in days
getDaysToRestoke // time in days to restoke
```

## Factory params
```
search(params: InventorySearchParams) => INVENTORY[]
```

**Comment by halk** [comment]
Glad to see this getting started.

I think the main challenge will be to make it generic but also flexible enough so that it applies for all/most backends. What happens when a backend does not support e.g. days to restock and delivery time? Empty response?

I think the major missing point is multiwarehousing/locations. There are few considerations I have:
- Is this a filtering or getter schema problem? I see there is an inventory search param, is that for ID of inventory or ID of inventory location?
- what if we want a location independent information? In our case, in the past we were using the MAX(qtyLocation1, qtyLocation2) for general availability information and not go into location specifics yet
- some merchants may want to avoid deciding which location to use in the frontend

What if the inventory information is included in useProducts already?



You have a few typos:
- `getAvailebleQty` > `getAvailableQty`
- `getDaysToRestoke` and `restoke` in the comment > `getDaysToRestock` and `restock`

We might want a general isOnStock or isAvailable return member which returns boolean?
