### ISSUE TITLE
Totals not updated after logging in and merging cart

### ISSUE THREAD

**Issue by revlis-x** [vuestorefront/vue-storefront#5007]
## Current behavior
When a guest cart with items gets merged with previously added account cart items after login, cart totals are not updated.

## Expected behavior
Cart Totals should be updated after merging the cart,

## Steps to reproduce the issue
1. Have an account with items in cart and be logged out.
1. Put item in your guest cart.
1. Log-In
-> Items of both carts are merged but totals are not updated afterwards.

## Version of Vue Storefront
* [x] Vue Storefront 1.12.2, reproducible on https://demo.storefrontcloud.io/

## Additional information
`isTotalsSyncRequired` Getter is false when `updateTotalsAfterMerge` is called in this scenario.

**Comment by haideritx** [comment]
Facing the same issue. getting the isTotalsSyncRequired, which is causing the cart not to update the totals if magento value is updated and i call the 'cart/sync'

**Comment by pschaub** [comment]
We have seen this issue also in our project so I've tried to debug it.

Disclaimer: I am not an expert in `vue-storefront` yet. So everything I write here could be wrong.

## What I found
1. The function `updateTotalsAfterMerge` is checking for `getters.isTotalsSyncRequired`, which is `true` because the cart hash changed.
2. It triggers the dispatch `syncTotals`
3. Inside `syncTotals` the `getters.isTotalsSyncRequired` is still `true`
4. It triggers the dispatch `pullMethods`
5. Inside `pullMethods ` the `getters.isTotalsSyncRequired` is still `true`
6. It triggers the dispatch `syncShippingMethods`
7. **After the dispatch of `syncShippingMethods` finished, the `getters.isTotalsSyncRequired` is `false` instead of `true`.**
8. **The function `syncTotals` will NOT continue because `getters.isTotalsSyncRequired` is `false`. But we would expect that it should continue, we want a sync.**

I think the bug has been added through the change https://github.com/DivanteLtd/vue-storefront/pull/4387. With this change the cart hash is changed too early.

## Workaround

Inside `updateTotalsAfterMerge` we are using `syncTotals`.
There we could add the parameter `{ forceServerSync: true }` to force the server sync:
```
if (getters.isTotalsSyncRequired && clientItems.length > 0) {
  await dispatch('syncTotals', { forceServerSync: true })
}
```

## Remaining questions

 - Why is the cart hash changing back to the old cart hash?
 - Am I understanding the code correctly or is there a general mistake in my debugging?

**Comment by revlis-x** [comment]
@pschaub I came to the same workaround with `forceServerSync: true` when i debugged this. Thanks for your time to write this down.
I just wanted to add, I also had to `await` the 'addItem' calls in `mergeServerItem` to make i work consistently...

**Comment by pschaub** [comment]
@revlis-x thank you for the hint. I've created an additional issue to be sure that the missing `await` will be investigated: https://github.com/DivanteLtd/vue-storefront/issues/5165
