### ISSUE TITLE
Caching mechanism (SSR content)

### ISSUE THREAD

**Issue by andrzejewsky** [vuestorefront/vue-storefront#5139]
Caching layer is the most common way to achieve better performance and take off the high loads from the servers. In the web-dev world, the heaviest part of the app is actually a server-side rendering - the virtual DOM must be created along with corresponding data and that takes time. Due to efficiency reasons, a well-known approach to solve it is of course caching for pre-rendered markup.

## How we can cope with that?
Each time, we request the markup from the server, once is rendered we can store it in some sort of storage (redis, cdn, memcache etc) so the next request will be reading that markup from the storage instead. That will reduce rendering time significantly which also will impact the performance scoring. 

Obviously, we need to have an invalidation strategy, and for that purpose, we can introduce HTTP tagging. When we reach a page, we add a special HTTP header that contains tags which are describing the data related to that page. It can be an id of the product, category id, the list of the ids (category page), and more. 

On the backend, we are storing that markup, under the tags we sent so we exactly know, what what's the relation between data needs and the given page.

Clearly, the invalidation process is able to use these tags to purge the cache so the app will re-render this again. That mechanism will share a special endpoint for invalidating where, by given tags, you can purge the cache. That endpoint can be used by the eCommerce platform as a webhook (update product, call webhook, clean cache)

## The API
Of course, we need to provide an API for the developer to provide any cache adapter. However, we need to provide tools for tagging and configuring the whole cache.

### Nuxt module
Everything starts with a nuxt-module. By using this you register a cache with a given adapter. 

```
    ['@vue-storefront/nuxt-cache/nuxt', {
      invalidateEndpoint: '/invalidate-cache',
      adapter: [
       '@vue-storefront/cache-redis',
        {
          uri: 'redis://localhost',
          user: 'root'
        }
      ]
    }],
```

### Taging
The next step is a tagging function. I suggest to create here a dedicated composable function, so on each page, you can decide what tag you want to add.

```js
import { useCache } from '@vue-storefront/nuxt-cache'

const { setTags } = useCache();

setTags([P123 P456 P678]) 
setTags(() => [P123 P456 P678]) // alternatively callback, prevent generating tags on csr

```

That's the easiest way to do this as we always reading and manipulating the data inside of `setup() `method, so we always have an access to the properties we need to generate tag names.

### Write adapter
Depending on the needs we may have an API to write our own way of storing, reading, and invalidating the cache based on given tags so that's why adapters are built for. It requires a few functions, each dedicated to the corresponding process:

Example for Redis

```js
const RedisAdapter = (config) => {
  const redis = new Redis(config)

  // it reads or save the cache, depending on the purpose and source of the cache
  const invoke = async ({ req, res, tags, render }) => {
     if (redis.has(tags)) {
       return redis.get(tags)
     }

    redis.save(tags, render())

    return payload
  }

  // invalidates data, available in the endpoint /invalidate-cache
  const invalidate = async ({ req, res, tags }) => {
    redis.delete(tags)
  }

  return {
    invoke,
    invalidate
  };
}
```

┆Issue is synchronized with this [Jira Story](https://vsf.atlassian.net/browse/NEXT-369) by [Unito](https://www.unito.io/learn-more)

**Comment by Fifciu** [comment]
```ts
interface CacheAdapter {
  invoke: ({ req, res, tags, render }) => Promise<string>;
  invalidate: ({ req, res, tags }): Promise<Boolean>; // Success or not?
}
```

**Comment by Fifciu** [comment]
We also need a strategy **users**. As we are handling session via cookie, we have user subjective markup in SSR Output, contrary to vsf1

**Comment by filrak** [comment]
I really like the approach, I don't like the API (so nothing new here^^). I feel that this approach is lacking consistancy with what we already have in the repo and therefore adds to overall complexity and makes it ahrder to maintain this feature (and all future ones). It's important to handle similar things the same way if thats possible

A couple of thoughts and proposed APIs.

### Public API

First of all the thing that influences cache tags are products/categories/cms content/some custom data sources within a page. These are directly mapping to composables (product - useProduct, category - useCategory etc).

Therefore Composables should be responsible for setting  the cache tags OOTB. This will be the most common approach and if we don't do this this way users will have to write a lot of unnecessary boilerplate.
```js
const { search } = useProduct()

search({ id: '123' }) // adds `P123` or array of variants to cache tags or whatever it has to
```

Of course this configuration wont work for everyone so there has to be a way of configuring it.

Since setting the cache tags is not a Vue feature (not an integration) per se I don't see a value of embracing Vue reactivity here. To me its the same category of feature as Logger (and we should look at its API and approach the same way).

Also we always have to put tags in the context (url).

Therefore I suggest the following API:
```js
import { serverCache } from '@vue-storefront/core` // we will have `clientCache` as well later

serverCache.getTags(url) // see a list of tags for a given url 
serverCache.addTags(['P123']')
serverCache.setTags(url, tags => {
  tags.push('P123')
return tags
} // to just modify the current tag list

```

So the general example for a full page could look like this
```js
const $product = useProduct()
const $category = useCategory()

// composables are handling the default scenario
$product .search({ id: '123' }) // adds `P123` or array of variants to cache tags or whatever it has to
$category.search({ id: '123' }) // can be sth like `C123`

// then we can manage the tags and customize them if we want to
serverCache.setTags($route.fullPath, tags => {
  tags.push('CUSTOMTAG')
  return tags
}
``

### Integrator API

Next question is how we can make this feature possible for the integrators? Turns out the answer is simple and we can do this from core factories.

Let's take product as an example. The only thing that we need from integrators is basically how to get the UUID of a product so it can put in the cache tag.

```js
const factoryParams = {
  getProductUUID: (product) = {
    // example implementation
    return product.id
  }
}
```
We will need the same for categories, cms content etc.

### Core API

In the core these cache tags will be ahndled exactly as logger:

```js
    const search = async (params: PRODUCT_SEARCH_PARAMS, customQuery?: CustomQuery) => {
      Logger.debug('useProduct.search', params);

      loading.value = true;
      filters.value = null;
      try {
        const { data, total, availableFilters, availableSortingOptions } = await factoryParams.productsSearch(params, customQuery);
        products.value = data;
        serverCache.setTags(getCurrentInstance().options.$route.fullPath, tags => {
           products.value.forEach(product => tags.push('P' + factoryParams.getProductUUID(product)))
        })
        totalProducts.value = total;
        filters.value = availableFilters || null;
        sortingOptions.value = availableSortingOptions || null;
      } catch (e) {
        Logger.error('useProduct.search', e);
      } finally {
        loading.value = false;
      }
    };
```

**Comment by Fifciu** [comment]
Looks great. However, I have a few questions @filrak 
1. Shouldn't we use maybe getUniqueIndentifier**S**? I mean that product could be a `configurable` one (like in magento2) and has e.g. 6 variants with different ids. So we should have tag from configurable + 6 tags from variant = 7 tags for PDP
2. ```
serverCache.setTags($route.fullPath, tags => {
  tags.push('CUSTOMTAG')
  return tags
}
```
Why url? I think we do not need it.

**Comment by andrzejewsky** [comment]
full example:

```js
// nuxt module config
['@vue-storefront/nuxt' {
  cache: {
     server: '@vsf-enterprise/server-cache-redis'
  }
}]


// factory params
const factoryParams = {
  getUniqueIdentifiers: (response) {
    // generating identifiers based on the response
    return response.results.map(v => `${v.id}-${v.version}`)
  }
}

// core
const search = async (params: PRODUCT_SEARCH_PARAMS, customQuery?: CustomQuery) => {
  Logger.debug('useProduct.search', params);
  loading.value = true;
  try {
    const { data } = await factoryParams.productsSearch(params, customQuery);
    products.value = data;
    serverCache.setTags(factoryParams.getUniqueIdentifier(data))
  } catch (e) {
    Logger.error('useProduct.search', e);
  } finally {
    loading.value = false;
  }
};

// in project
const $product = useProduct()
const $category = useCategory()
// const { setTags } = useCache() // just idea

// composables are handling the default scenario
$product.search({ id: '123' }) // adds [`P123`], all tags: [`P123`]
$category.search({ id: '123' }) // adds [`C123`], all tags: [`P123`, `C123`]

// then we can manage the tags and customize them if we want to
serverCache.setTags(tags => [...tags, 'X123']) // adds [`X123`], all tags: [`P123`, `C123`, `X123`]
```

**Comment by Fifciu** [comment]
I know it is a bit too much about the future. I just want to emphasize that we should implement Tags as an instance of `Set`, we should mostly use `add` & `remove` operations and recommend them. `set` **action** should be available but used only if really necessary. Otherwise, some developer earlier or later will remove tags somewhere and possibly will learn it few months later :D 

Tell me if you need any disadvantages

**Comment by Fifciu** [comment]
1. Add plugin/module `cache.js` in nuxt-module/lib/module.js
2. Prepare nuxt-module/lib/plugins(or module)/cache.js
3. ~~Create middleware that will add a header with tags to the response (i could base on https://github.com/MartinLG/nuxt-custom-headers/blob/master/middleware.js). I should be able to add it from plugin (i could base on packages/ct/composables/nuxt/plugin.js).~~ Ok, I cannot use middleware - because it is being called before `setup` in components. Looking here: https://nuxtjs.org/docs/2.x/internals-glossary/internals-renderer#hooks I see `render:route` should do the job. Still not sure if I can use plugin there, probably I will be forced to use use the module instead.
4. In core/core/src/utils/cache/index.ts I should create and export some object like:
```ts
const serverCacheFactory = () => {
  let tagsList = new Set<string>();

  const getTags = () => Array.from(tagsList);
  const addTags = tags => tags.map(tag => tagsList.add(tag))
  const setTags = cb => cb(tagsList)

  return {
    getTags,
    addTags,
    setTags
  }
}

export const serverCache = serverCacheFactory();
```
5. Export it from `core` as a `serverCache`.
6. In composables I will use `serverCache.addTags` as showed in API above
7. In file from 3rd step - in render:route hook I will use `getTags` and add some response header.

Added response header should be configurable imo. Wdyt?

**Comment by andrzejewsky** [comment]
UPDATE:

### Invalidators
As invalidating can be different per integration and we want to have an agnostic driver, the invalidators should be provided by the integration. The goal for invalidator is to provide tags that need to be invalidated.

```
['@vue-storefront/nuxt'. {
  cache: {
    server: {
      ['@vsf-enterprise/cache-redis', {
          invalidators: [commercetools, algolia, ]
        }
      }]
    }
  }
}]

inside of the Driver:

const invalidate = async ({ req, res }) => {
  const tags = determineTagsToInvalidate(req, res)
  redis.delete(tags)
}
```

### Cache tags types:

```ts
enum CachePrefix {
  Product = 'P'
  Category = 'C'
}

interface CacheTag {
  predix: CachePrefix;
  value: string;
}

// extending in integration
declare module "@vue-storefront/core" {
  enum  CachePrefix {
  }
}
```

### getUniqueIdentifiers -> getCacheTags

```ts
getCacheTags<T>(response: T) => CacheTags[]
```

**Comment by filrak** [comment]
@andrzejewsky please propose the final API and flow based on the our previous discussions and we're ready to start :)
