### ISSUE TITLE
Can't go to the Payment checkout step

### ISSUE THREAD

**Issue by filrak** [vuestorefront/vue-storefront#5385]
![image](https://user-images.githubusercontent.com/15185752/103930248-bc014280-511e-11eb-9465-c1a0c4400485.png)
Click "select shipping method"
see error in console
![image](https://user-images.githubusercontent.com/15185752/103930305-cfaca900-511e-11eb-9608-6804d325b6d4.png)

**Comment by Fifciu** [comment]
It is important to also check if we can go from Billing step to Order Review step. I am 99% sure - we can't. Problem appears due to changes in SFUI & bad handling it inside our app. 

As far as I remember, in country select (`pages/Checkout/Shipping.vue` line 94) we have to change @selected to @input, e.g:
```js
@input="setShippingDetailsAndUnpickAddress({ country: $event })"
```

Also as a workaround during work on CKO, in line 118 of `pages/Checkout/Payment.vue` I used:
```js
:value="billingDetails.phone || billingDetails.contactInfo.phone"
```

**Comment by bloodf** [comment]
This issue has been closed due to inactivity. 

If you want to re-open the issue, please re-create the issue, and post newer information on this problem.
