### ISSUE TITLE
PDP Bugs and weird behavior

### ISSUE THREAD

**Issue by Fifciu** [vuestorefront/vue-storefront#5513]
## Current behavior

Desktop

1. Nothing happens click Read all reviews
1. Nothing happens click Size Guide
1. Changing product's size causes ugly blink of font
1. Why `Category` in Description Tab is Btn-like but does not have any anchor?
1. We can add any number of item to the cart. I've just added 112312 TShirts, Total price is `-$13,640,400,021,068,508.00`. We should add some limit: 
![image](https://user-images.githubusercontent.com/30155292/107400772-71e6f480-6b02-11eb-82b8-57e6ca7b05ff.png)
1. Breadcrumbs links are bad. Each one points to current's view
1. On width < 1100  we can see only part of the price. It happens only with certain products, e.g: https://vsf-next-demo.storefrontcloud.io/p/38143c0c-c9b0-448c-93cd-60eb90d8da57/aspesi-shirt-h805-white

Mobile

1. Getting DOMExceptions on every view (but only locally on next branch)
1. Nothing happens after clicking `Menu` in bottom nav
1. Double images on mobile (or maybe it should be like that?): 
![image](https://user-images.githubusercontent.com/30155292/107400648-47953700-6b02-11eb-907b-fede50136edb.png)
1. Bottom Nav overlays on last item of footer menu
1. Opening Cart on PDP does not add scroll lock on the body

**Comment by filrak** [comment]
Desktop
1,2 - its not there yet, we need prerequisites to fix that
3 - to solve
4 - should be regular text
5 - I don't think there should be a limit but I'm curious why there is a negative num
6 - there is another issue and discussion about this, to;dr we can't get this path from the product itself, it has to be passed as query param
7 - probably this should be an issue on SFUI repo

Mobile
1 - should be fixed
2 - There is a PR from @lukaszjedrasik but afaik its blocked due to custom query not working
3 - yup it should be like that, its a thumb
4 - should be fixed
5 - should be fixed

I advise to create a separate issues for D1,2,7 (to check) M2,3  (if they are not there yet) and remove those points from this list.

Rest should be fixe

**Comment by gibkigonzo** [comment]
Mobile pt 1 => `mapMobileObserver` requires window so it will work only on client side. Maybe it should use userAgent like in vsf1 :thinking: So errors may exist in a few places. For example one error is in `SfHeaderNavigationItem` line with `v-if="!isVisibleOnMobile"`. But I thnik there are more places. This problem needs to be solved in sfui :shrug:

**Comment by AdamPawlinski** [comment]
@gibkigonzo thanks for a tip. We found this error in other places too. We'll take care of it in 0.11.0 release of SFUI.

**Comment by AdamPawlinski** [comment]
ad. Desktop 7 
I'll make an issue on SFUI for it. Thanks.

**Comment by AdamPawlinski** [comment]
ad. mobile 5 
There is laready issue for that https://github.com/vuestorefront/vue-storefront/issues/5514

**Comment by AdamPawlinski** [comment]
There is also issue with blinking when you click on add to cart button (quantity selector disappears for a moment). It can be added as one issue with Desktop 3 issue.
