### ISSUE TITLE
Missing Types (Next) - Master Thread

### ISSUE THREAD

**Issue by filrak** [vuestorefront/vue-storefront#5518]
### `useUiHelpers`
* mostly returns `any`

### `useUiState`
* mostly returns `any`

### `useReview`
* `reviewGetters.getItems` returns `any`

**Comment by filipsobol** [comment]
## `load` in `UseCartFactoryParams`
  * `customQuery` is `any`, but should be `CustomQuery`
  * `quantity` is `any`, but should be `number | string`


## `searhAddresses` in `UseUserAddress`
* `params` should be `Record<string, any>` to be consistent with other types

## Inconsistent function types
Function types in `types.ts` are inconsistent - some use `methodName: () => any`, others `methodName(): any`. I propose use of the latter, because it's shorter.

**Comment by bloodf** [comment]
This issue has been closed due to inactivity. 

If you want to re-open the issue, please re-create the issue, and post newer information on this problem.
