### ISSUE TITLE
[BUG] My profile

### ISSUE THREAD

**Issue by justyna-13** [vuestorefront/vue-storefront#5537]
1. In My newsletter section save changes button doesn't work
1. Without JS there's no data at all 
![Screenshot from 2021-02-15 08-09-56](https://user-images.githubusercontent.com/46591755/107915991-cb697c00-6f65-11eb-91c9-247ca3224ff3.png)

**Comment by Baroshem** [comment]
@justyna-13 I think it will be better to split this task into separate ones. Implementing Newsletter functionality is already a breaking change and new feature on its own. The problem with not displaying account content with JS disabled seems like a different issue (maybe even caused by Storefront UI, I would have to check). I created another issue specifically for that.

**Comment by bloodf** [comment]
This issue has been closed due to inactivity. 

If you want to re-open the issue, please re-create the issue, and post newer information on this problem.
