### ISSUE TITLE
Compare with magento pwa

### ISSUE THREAD

**Issue by j209** [vuestorefront/vue-storefront#5547]
How we can compare vsf with [magento pwa studio](https://github.com/magento/pwa-studio)?

**Comment by clinton-origin** [comment]
This is interesting as I was aware of Magento PWA but thought it was somehow tacked onto the CMS. This does seem to be a separate system like vue storefront. 

I would say this system will be more fully integrated with Magento and seems to be more actively worked on since it's in version 8 already.

However, there is a big drawback with it in that it only supports 1 payment gateway whereas vue storefront already has a lot of other gateways to choose from. They may have others but they might not be tested properly.

Personally, I prefer the way we have it set up where the system redirects to the Magento standard checkout which gives us the flexibly of using battle-hardened payment plugins.

If I hadn't dedicated a year already to vue storefront I would have probably gone with the Magento one simply because we only use it for the Magento CMS whereas vue storefront is trying to support a wide range of platforms other than Magento.

**Comment by bloodf** [comment]
This issue has been closed due to inactivity. 

If you want to re-open the issue, please re-create the issue, and post newer information on this problem.
