### ISSUE TITLE
How do I override this file ?     core\modules\cart\index.ts

### ISSUE THREAD

**Issue by zzzheli** [vuestorefront/vue-storefront#5779]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. 
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Check our forum:
https://forum.vuestorefront.io/

# Is there something you don't understand? What is it? Describe it.	

# Can't find what you're looking for?

## Keep the problem description concise and include:
- [ ] A brief description of the problem,
- [ ] Where the problem is occurring,
- [ ] The length of time the problem has been occurring,
- [ ] The size of the problem.

## Additional information

![1](https://user-images.githubusercontent.com/40748500/115104048-a3f45700-9f88-11eb-9aca-dede3e04115e.png)

I want to modify the code here, how do I modify it in my extension file

**Comment by Fifciu** [comment]
If you want to create your own `CartModule: StorefrontModule` function:
- Create a new module in src/modules with this `core/modules/cart/index.ts` file as a base, fix the import paths, and use CartModule from src/modules/your-module instead of `core/modules/cart` in your src/modules/client.ts or index.ts.

If you want to overwrite `load` action: https://docs.vuestorefront.io/v1/guide/cookbook/module.html#_2-2-recipe-b-override-vuex-store-with-extendstore
